### ISSUE TITLE
test_variance_weight fails

### ISSUE THREAD

**Issue by ohadle** [yandexdataschool/roc_comparison#1]
10/11 unit tests pass, but this one fails:
```
Failure
Traceback (most recent call last):
  File "C:\Users\ohadl\AppData\Local\Continuum\anaconda3\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\ohadl\AppData\Local\Continuum\anaconda3\lib\unittest\case.py", line 615, in run
    testMethod()
  File "C:\Users\ohadl\repos\PythonUtils\test\roc_comparison\test.py", line 133, in test_variance_weight
    numpy.testing.assert_allclose(variances.mean(), aucs.var(), rtol=0.1)
  File "C:\Users\ohadl\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\testing\_private\utils.py", line 1452, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "C:\Users\ohadl\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\testing\_private\utils.py", line 789, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.1, atol=0

(mismatch 100.0%)
 x: array(0.013752)
 y: array(0.017002)
```

Not sure what the implications are.

**Comment by kazeevn** [comment]
Unfortunately, the implications are that the math for the error in the weighted case is more difficult, simply adding weights to the fast DeLong algorithm, like I did here, is incorrect. If there is a paper on the issue, I'd much appreciate it. Meanwhile, I'll clean the master branch from the weighted code.

**Comment by kazeevn** [comment]
Removed the weighted code in 7eab86b653491601cd3af5be1e47ae843016c0cb
